In [2]:
import pandas as pd

In [4]:
df1 = pd.read_csv('data/cybersecurity_threat_detection.csv')
df2 = pd.read_csv('data/cyber_attack_dataset_100000.csv')

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            10000 non-null  object
 1   src_ip               10000 non-null  object
 2   dst_ip               10000 non-null  object
 3   src_port             10000 non-null  int64
 4   dst_port             10000 non-null  int64
 5   protocol             10000 non-null  object
 6   bytes_sent           10000 non-null  int64
 7   bytes_received       10000 non-null  int64
 8   user_agent           10000 non-null  object
 9   url                  6768 non-null   object
 10  is_internal_traffic  10000 non-null  bool
 11  label                10000 non-null  int64
 12  attack_type          10000 non-null  object
dtypes: bool(1), int64(5), object(7)
memory usage: 947.4+ KB

In [11]:
df1.head()

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68.59.26.43,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:25:46,119.204.243.78,90.28.90.234,14948,1433,TCP,316502,38571,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN,False,0,benign
3,2025-10-01 00:27:21,122.119.194.175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
4,2025-10-01 00:40:09,181.199.242.68,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   duration       100000 non-null  int64
 1   src_bytes      100000 non-null  int64
 2   dst_bytes      100000 non-null  int64
 3   packet_count   100000 non-null  int64
 4   protocol       100000 non-null  object
 5   failed_logins  100000 non-null  int64
 6   attack_type    100000 non-null  object
dtypes: int64(5), object(2)
memory usage: 5.3+ MB

In [13]:
df2.head()

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
0,1,8605,418,631,TCP,0,DDoS
1,1,499,148,131,UDP,0,PortScan
2,10,370,160,105,UDP,0,PortScan
3,2,5138,320,666,TCP,0,DDoS
4,36,524,467,58,UDP,10,BruteForce

In [17]:
cat_cols = df2.select_dtypes(exclude='number').columns.tolist()

for col in cat_cols:
    print(col)
    print(sorted(map(repr,df2[col].dropna().unique())))
    print()

protocol
["'TCP'", "'UDP'"]

attack_type
["'BruteForce'", "'DDoS'", "'Normal'", "'PortScan'"]

In [18]:
df1['attack_type'].unique()

array(['benign', 'port-scan', 'sql-injection', 'c2',
       'credential-stuffing', 'brute-force', 'command-injection', 'xss',
       'ddos', 'exploit-attempt'], dtype=object)

In [28]:
df2['src_bytes'].max()

10000

In [30]:
df2['src_bytes'].min()

50

In [29]:
df1['bytes_sent'].max()

139170405

In [31]:
df1['bytes_sent'].min()

17